export { HeaderAuth } from './variants/auth/header-auth.component'
export { HeaderSearch } from './variants/search/header-search.component'
export { HeaderCard } from './variants/card/header-card.component'
export { HeaderTab } from './variants/tab/header-tab.component'
export { HeaderDefault } from './variants/default/header-default.component'
