export default {
  'montserrat-regular': require('~assets/fonts/Montserrat/Montserrat-Regular.ttf'),
  'montserrat-black': require('~assets/fonts/Montserrat/Montserrat-Black.ttf'),
  'montserrat-bold': require('~assets/fonts/Montserrat/Montserrat-Bold.ttf'),
  'montserrat-italic': require('~assets/fonts/Montserrat/Montserrat-Italic.ttf'),
  'montserrat-extra-light': require('~assets/fonts/Montserrat/Montserrat-ExtraLight.ttf'),
  'montserrat-extra-bold': require('~assets/fonts/Montserrat/Montserrat-ExtraBold.ttf'),
  'montserrat-light': require('~assets/fonts/Montserrat/Montserrat-Light.ttf'),
  'montserrat-medium': require('~assets/fonts/Montserrat/Montserrat-Medium.ttf'),
  'montserrat-semi-bold': require('~assets/fonts/Montserrat/Montserrat-SemiBold.ttf'),
  'montserrat-thin': require('~assets/fonts/Montserrat/Montserrat-Thin.ttf'),
  'montserrat-black-italic': require('~assets/fonts/Montserrat/Montserrat-BlackItalic.ttf'),
  'montserrat-bold-italic': require('~assets/fonts/Montserrat/Montserrat-BoldItalic.ttf'),
  'montserrat-extra-bold-italic': require('~assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf'),
  'montserrat-extra-light-italic': require('~assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf'),
  'montserrat-light-italic': require('~assets/fonts/Montserrat/Montserrat-LightItalic.ttf'),
  'montserrat-medium-italic': require('~assets/fonts/Montserrat/Montserrat-MediumItalic.ttf'),
  'montserrat-semi-bold-italic': require('~assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf'),
  'montserrat-thin-italic': require('~assets/fonts/Montserrat/Montserrat-ThinItalic.ttf'),
}
